// Mock data for dashboard UI — replace with real DB queries once database is set up

export const mockUser = {
  id: "user_1",
  name: "John Doe",
  email: "john@devstash.demo",
  image: null,
  isPro: false,
};

export const mockItemTypes = [
  { id: "type_snippet",  name: "snippet",  icon: "Code",       color: "#3b82f6", isSystem: true },
  { id: "type_prompt",   name: "prompt",   icon: "Sparkles",   color: "#8b5cf6", isSystem: true },
  { id: "type_note",     name: "note",     icon: "StickyNote", color: "#fde047", isSystem: true },
  { id: "type_command",  name: "command",  icon: "Terminal",   color: "#f97316", isSystem: true },
  { id: "type_link",     name: "link",     icon: "Link",       color: "#10b981", isSystem: true },
  { id: "type_file",     name: "file",     icon: "File",       color: "#6b7280", isSystem: true },
  { id: "type_image",    name: "image",    icon: "Image",      color: "#ec4899", isSystem: true },
];

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    itemCount: 12,
    createdAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "col_2",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    itemCount: 9,
    createdAt: "2024-01-12T00:00:00Z",
  },
  {
    id: "col_3",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    itemCount: 5,
    createdAt: "2024-01-14T00:00:00Z",
  },
  {
    id: "col_4",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    itemCount: 24,
    createdAt: "2024-01-16T00:00:00Z",
  },
  {
    id: "col_5",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    itemCount: 15,
    createdAt: "2024-01-18T00:00:00Z",
  },
  {
    id: "col_6",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    itemCount: 18,
    createdAt: "2024-01-20T00:00:00Z",
  },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useAuth Hook",
    description: "Custom authentication hook for React applications",
    contentType: "TEXT" as const,
    content: `import { useSession } from 'next-auth/react';\n\nexport function useAuth() {\n  const { data: session, status } = useSession();\n  return {\n    user: session?.user,\n    isLoading: status === 'loading',\n    isAuthenticated: status === 'authenticated',\n  };\n}`,
    language: "typescript",
    isFavorite: false,
    isPinned: true,
    tags: ["react", "auth", "hooks"],
    itemTypeId: "type_snippet",
    collectionIds: ["col_1"],
    createdAt: "2024-01-19T00:00:00Z",
    lastUsedAt: "2024-01-19T00:00:00Z",
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    description: "Fetch wrapper with exponential backoff retry logic",
    contentType: "TEXT" as const,
    content: `export async function fetchWithRetry(url: string, retries = 3): Promise<Response> {\n  for (let i = 0; i < retries; i++) {\n    try {\n      const res = await fetch(url);\n      if (!res.ok) throw new Error(res.statusText);\n      return res;\n    } catch (err) {\n      if (i === retries - 1) throw err;\n      await new Promise(r => setTimeout(r, 2 ** i * 1000));\n    }\n  }\n  throw new Error('Max retries reached');\n}`,
    language: "typescript",
    isFavorite: false,
    isPinned: true,
    tags: ["api", "error-handling", "typescript"],
    itemTypeId: "type_snippet",
    collectionIds: ["col_1"],
    createdAt: "2024-01-19T00:00:00Z",
    lastUsedAt: "2024-01-19T00:00:00Z",
  },
  {
    id: "item_3",
    title: "Git Stash Workflow",
    description: "Save and restore uncommitted changes",
    contentType: "TEXT" as const,
    content: "git stash\ngit stash pop\ngit stash list\ngit stash drop stash@{0}",
    language: null,
    isFavorite: true,
    isPinned: false,
    tags: ["git", "workflow"],
    itemTypeId: "type_command",
    collectionIds: ["col_5"],
    createdAt: "2024-01-18T00:00:00Z",
    lastUsedAt: "2024-01-18T00:00:00Z",
  },
  {
    id: "item_4",
    title: "System Prompt — Code Reviewer",
    description: "AI system prompt for reviewing pull requests",
    contentType: "TEXT" as const,
    content: "You are an expert code reviewer. Review the provided code for bugs, security issues, performance problems, and maintainability. Be concise and specific.",
    language: null,
    isFavorite: true,
    isPinned: false,
    tags: ["ai", "code-review"],
    itemTypeId: "type_prompt",
    collectionIds: ["col_6"],
    createdAt: "2024-01-20T00:00:00Z",
    lastUsedAt: null,
  },
  {
    id: "item_5",
    title: "Python List Comprehension Patterns",
    description: "Common list comprehension examples",
    contentType: "TEXT" as const,
    content: "# Filter\nevens = [x for x in range(10) if x % 2 == 0]\n\n# Transform\nsquares = [x**2 for x in range(10)]\n\n# Nested\nmatrix = [[1,2],[3,4]]\nflat = [n for row in matrix for n in row]",
    language: "python",
    isFavorite: false,
    isPinned: false,
    tags: ["python", "list-comprehension"],
    itemTypeId: "type_snippet",
    collectionIds: ["col_2"],
    createdAt: "2024-01-12T00:00:00Z",
    lastUsedAt: null,
  },
  {
    id: "item_6",
    title: "Next.js Project Context",
    description: "Project overview for AI assistants",
    contentType: "TEXT" as const,
    content: "# Project Context\nThis is a Next.js 15 app using the App Router, TypeScript, Tailwind CSS v4, and Prisma with PostgreSQL.",
    language: "markdown",
    isFavorite: false,
    isPinned: false,
    tags: ["context", "next.js", "ai"],
    itemTypeId: "type_note",
    collectionIds: ["col_3"],
    createdAt: "2024-01-14T00:00:00Z",
    lastUsedAt: null,
  },
];

// Sidebar counts — matches the type totals shown in the dashboard sidebar
export const mockItemTypeCounts: Record<string, number> = {
  snippet: 24,
  prompt: 18,
  command: 15,
  note: 12,
  file: 5,
  image: 5,
  link: 8,
};
